pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - label=auto-merge-upon-passing-tests
    actions:
      merge:
        method: merge

pull_request_rules:
  - name: delete head branch on merged pull requests
    conditions:
      - merged
    actions:
      delete_head_branch:

pull_request_rules:
  - name: delete head branch on closed pull requests
    conditions:
      - closed
    actions:
      delete_head_branch: