#ifndef BALANCED_MOTION_2__MOTION_DEFS_HPP_
#define BALANCED_MOTION_2__MOTION_DEFS_HPP_

#define MOTION_DT 0.02
#define MOTION_DT_MS (MOTION_DT * 1000)

#define STANDING_HIPH 0.248

#define CROUCHING_HIPH 0.23

#define BASE_LEG_LIFT 0.012

#define BASE_WALK_PERIOD 0.25

#endif  // BALANCED_MOTION_2__MOTION_DEFS_HPP_