team_ijnek:
  1:
    x: -5.0
    y: -2.0
    theta: 0.0

  2:
    x: -5.0
    y: -1.0
    theta: 0.0

  3:
    x: -5.0
    y: 0.0
    theta: 0.0

  4:
    x: -5.0
    y: 1.0
    theta: 0.0

  5:
    x: -5.0
    y: 2.0
    theta: 0.0

team_opponent:
  1:
    x: -5.0
    y: -2.0
    theta: 0.0

  2:
    x: -5.0
    y: -1.0
    theta: 0.0

  3:
    x: -5.0
    y: 0.0
    theta: 0.0

  4:
    x: -5.0
    y: 1.0
    theta: 0.0

  5:
    x: -5.0
    y: 2.0
    theta: 0.0